version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: slot-postgres
    environment:
      POSTGRES_DB: slotdb       # <--- ASTA creeaza baza de date automat!
      POSTGRES_USER: postgres   # Userul
      POSTGRES_PASSWORD: password # Parola
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: