server:
  port: 8085           # Port HTTP (Punem 8085 ca sa fim siguri ca e liber)

spring:
  application:
    name: rng-service

grpc:
  server:
    port: 9091         # <--- CRITIC! Aici trebuie sa fie 9091, ca sa coincida cu ce cauta Game Service