server:
  port: 8082

spring:
  application:
    name: game-service

grpc:
  server:
    port: 9092
  client:
    # Aici configuram clientul pentru RNG (Zarul)
    rng-service:
      address: static://localhost:9091
      negotiation-type: plaintext
    # Aici configuram clientul pentru Data (Seiful)
    data-service:
      address: static://localhost:9093
      negotiation-type: plaintext
