server:
  port: 8082

spring:
  application:
    name: game-service

grpc:
  server:
    port: 9092
  client:

    rng-service:
      address: static://localhost:9091
      negotiation-type: plaintext

    data-service:
      address: static://localhost:9093
      negotiation-type: plaintext
